apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  app: helloweb

namespace: helloweb

resources:
- issuer.yaml
- certificate.yaml

patchesStrategicMerge:
- ingress.yaml

configurations:
- cert-manager-configuration.yaml